CREATE TABLE "Customer" (
  "CustomerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar,
  "LastName" varchar,
  "Email" varchar UNIQUE,
  "PhoneNumber" varchar,
  "Address" text
);

CREATE TABLE "Categories" (
  "CategoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" varchar UNIQUE
);

CREATE TABLE "Books" (
  "BookID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar,
  "Author" varchar,
  "Publisher" varchar,
  "Price" decimal,
  "ISBN" varchar UNIQUE,
  "CategoryID" int
);

CREATE TABLE "CustomerBook" (
  "CustomerID" int,
  "BookID" int,
  "PurchaseDate" timestamp
);

ALTER TABLE "Books" ADD FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("CategoryID");

ALTER TABLE "CustomerBook" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customer" ("CustomerID");

ALTER TABLE "CustomerBook" ADD FOREIGN KEY ("BookID") REFERENCES "Books" ("BookID");
